name: Harvard Extension
title: Harvard Extension Reunion
logo: /images/headshot.png
description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.
theme: jekyll-theme-minimal
